import { createRequire } from 'node:module';
import path from 'node:path';
import { promises as fs } from 'node:fs';
const require = createRequire(import.meta.url);
const rspack = require(require.resolve('@rspack/core', { paths: [process.cwd()] }));

import { discoverPlugins } from './PluginDiscovery.mjs';
import { generateWrapperModules } from './WrapperModuleGenerator.mjs';
import { createModuleReplacements } from './ModuleReplacementFactory.mjs';
import { injectEntry } from './PluginEntryInjector.mjs';

// Helper to generate the static plugin-metadata.ts file at build-time
async function generateMetadata(plugins, outputDir) {
  await fs.mkdir(outputDir, { recursive: true });
  let importsContent = '';
  let pluginsArrayContent = 'export const plugins = [\n';
  let storeDecorationsContent = 'export const storeDecorations = [\n';

  let importCounter = 0;

  for (const plugin of plugins) {
    const hasEntry = await fs.access(path.join(plugin.pluginDir, 'dist', 'index.js')).then(() => true).catch(() => false);
    let entryImportVar = 'null';
    if (hasEntry) {
      entryImportVar = `entry_${plugin.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
      const absoluteEntryPath = path.join(plugin.pluginDir, 'dist', 'index.js');
      importsContent += `import ${entryImportVar} from '${absoluteEntryPath}';\n`;
    }

    // Stylesheet imports
    const styles = plugin.manifest.targets?.app?.styles || [];
    for (const style of styles) {
      const absoluteStylePath = path.resolve(plugin.pluginDir, style.file);
      importsContent += `import '${absoluteStylePath}';\n`;
    }

    // Route imports
    const routes = plugin.manifest.targets?.app?.routes || [];
    const routeConfigs = [];
    for (const r of routes) {
      const jsFile = r.component.replace(/\.tsx?$/, '.js');
      const absoluteComponentPath = path.resolve(plugin.pluginDir, 'dist', jsFile);
      const routeImportVar = `route_${importCounter++}`;
      importsContent += `import ${routeImportVar} from '${absoluteComponentPath}';\n`;
      routeConfigs.push({
        path: r.path,
        parentRoute: r.parentRoute,
        component: routeImportVar,
      });
    }

    // Store decorators imports
    const stores = plugin.manifest.targets?.app?.stores || [];
    const storeConfigs = [];
    for (const s of stores) {
      const jsFile = s.decorator.replace(/\.ts$/, '.js');
      const absoluteDecoratorPath = path.resolve(plugin.pluginDir, 'dist', jsFile);
      const decoratorImportVar = `decorator_${importCounter++}`;
      const storeImportVar = `store_${importCounter++}`;

      importsContent += `import ${decoratorImportVar} from '${absoluteDecoratorPath}';\n`;
      importsContent += `import ${storeImportVar} from '@app/${s.target}';\n`;

      storeConfigs.push({
        store: storeImportVar,
        decorator: decoratorImportVar,
        target: s.target,
      });
    }

    // Build the plugins array entry
    pluginsArrayContent += `  {\n`;
    pluginsArrayContent += `    name: ${JSON.stringify(plugin.name)},\n`;
    pluginsArrayContent += `    entry: ${entryImportVar},\n`;
    pluginsArrayContent += `    routes: [\n`;
    for (const rc of routeConfigs) {
      pluginsArrayContent += `      { path: ${JSON.stringify(rc.path)}, parentRoute: ${JSON.stringify(rc.parentRoute)}, component: ${rc.component} },\n`;
    }
    pluginsArrayContent += `    ]\n`;
    pluginsArrayContent += `  },\n`;

    // Build the store decorations array entries
    for (const sc of storeConfigs) {
      storeDecorationsContent += `  {\n`;
      storeDecorationsContent += `    store: ${sc.store},\n`;
      storeDecorationsContent += `    decorator: ${sc.decorator},\n`;
      storeDecorationsContent += `    target: ${JSON.stringify(sc.target)}\n`;
      storeDecorationsContent += `  },\n`;
    }
  }

  pluginsArrayContent += '];\n';
  storeDecorationsContent += '];\n';

  const fileContent = `// Auto-generated by Fluxer App Plugin Loader
${importsContent}
${pluginsArrayContent}
${storeDecorationsContent}
`;

  await fs.writeFile(path.join(outputDir, 'plugin-metadata.ts'), fileContent, 'utf-8');
}

export default async () => {
  const require = createRequire(import.meta.url);
  
  // 1. Resolve paths
  const appDir = path.resolve(import.meta.dirname, '../../fluxer_app');
  const appSrcDir = path.join(appDir, 'src');
  const outputDir = path.resolve(import.meta.dirname, './generated');
  const pluginsDir = process.env.FLUXER_PLUGIN_DIR || path.resolve(import.meta.dirname, '../../plugins');

  console.log(`[App Loader] Discovering plugins in: ${pluginsDir}`);

  // 2. Discover plugins at build time
  const plugins = await discoverPlugins(pluginsDir);
  console.log(`[App Loader] Discovered ${plugins.length} plugin(s) with targets.app`);

  // 3. Generate wrapper modules for component overrides
  const mappings = await generateWrapperModules(plugins, appSrcDir, outputDir);
  console.log(`[App Loader] Generated ${mappings.length} component wrapper module(s)`);

  // 4. Generate the plugin-metadata.ts containing static routing/styles/stores setup
  await generateMetadata(plugins, outputDir);

  // 5. Load original Rspack config
  const originalConfigFn = (await import('../../fluxer_app/rspack.config.mjs')).default;
  const config = originalConfigFn();

  // 6. Prepend bootstrap entrypoint
  const bootstrapPath = path.resolve(import.meta.dirname, './PluginBootstrap.ts');
  config.entry = injectEntry(config.entry, bootstrapPath);

  // 7. Inject module replacements
  const replacements = createModuleReplacements(rspack, mappings, appSrcDir);
  config.plugins = [
    ...(config.plugins || []),
    ...replacements,
  ];

  // 8. Add alias for generated directory and SDK
  config.resolve = config.resolve || {};
  config.resolve.alias = {
    ...config.resolve.alias,
    '@plugins-generated': outputDir,
    '@pekempy/fluxer-plugin-sdk': path.resolve(import.meta.dirname, '../sdk/src'),
  };

  // 9. Add fallback modules directories for resolving packages like 'react' outside the app folder
  config.resolve.modules = [
    ...(config.resolve.modules || ['node_modules']),
    path.join(appDir, 'node_modules'),
    path.join(appDir, '../node_modules'),
  ];

  return config;
};
