import { promises as fs } from 'node:fs';
import path from 'node:path';

export async function generateWrapperModules(plugins, appSrcDir, outputDir) {
  await fs.mkdir(outputDir, { recursive: true });
  const mappings = [];

  for (const plugin of plugins) {
    const components = plugin.manifest.targets?.app?.components || [];
    for (const comp of components) {
      const targetPath = comp.target; // e.g. "features/messaging/components/MessageContent/MessageContent"
      const wrapperPath = path.resolve(plugin.pluginDir, comp.wrapper);
      const wrapperImportPath = wrapperPath.replace(/\.(web\.)?[jt]sx?$/, '');

      // Find original file extension (.tsx, .ts, .jsx, .js)
      let originalExt = '';
      const extensions = ['.tsx', '.ts', '.jsx', '.js', '.web.tsx', '.web.ts'];
      let originalFullPath = '';
      
      for (const ext of extensions) {
        const testPath = path.join(appSrcDir, `${targetPath}${ext}`);
        try {
          await fs.access(testPath);
          originalExt = ext;
          originalFullPath = testPath;
          break;
        } catch {}
      }

      if (!originalFullPath) {
        console.error(`[App Loader] Error: Original component not found for target '${targetPath}'`);
        continue;
      }

      const componentName = path.basename(targetPath);
      const safeName = targetPath.replace(/[^a-zA-Z0-9]/g, '_');
      const wrapperFileName = `wrap__${safeName}.tsx`;
      const wrapperFilePath = path.join(outputDir, wrapperFileName);

      // We use import query ?original to bypass Rspack module replacement
      const originalImportPath = `${originalFullPath}?original`;

      // Read original file to detect what exports it defines
      const originalContent = await fs.readFile(originalFullPath, 'utf-8');
      const hasDefaultExport = originalContent.includes('export default');
      const hasNamedExport = originalContent.includes(`export const ${componentName}`) ||
                             originalContent.includes(`export function ${componentName}`) ||
                             originalContent.includes(`export class ${componentName}`) ||
                             new RegExp(`export\\s+\\{[^}]*\\b${componentName}\\b[^}]*\\}`).test(originalContent);

      let code = `// Auto-generated by Fluxer App Plugin Loader
import * as OriginalModule from '${originalImportPath}';
import PluginWrapper from '${wrapperImportPath}';
import React from 'react';
`;

      if (hasDefaultExport) {
        code += `
const OriginalDefault = (OriginalModule as any).default;
const WrappedDefault = React.forwardRef((props: any, ref: any) => {
  return React.createElement(PluginWrapper, {
    OriginalComponent: OriginalDefault,
    ref,
    ...props
  });
});
WrappedDefault.displayName = 'WrappedDefault(${componentName})';
export default WrappedDefault;
`;
      }

      if (hasNamedExport) {
        code += `
const OriginalNamed = (OriginalModule as any).${componentName};
export const ${componentName} = React.forwardRef((props: any, ref: any) => {
  return React.createElement(PluginWrapper, {
    OriginalComponent: OriginalNamed,
    ref,
    ...props
  });
});
(${componentName} as any).displayName = 'WrappedNamed(${componentName})';
`;
      }

      code += `\nexport * from '${originalImportPath}';\n`;

      await fs.writeFile(wrapperFilePath, code, 'utf-8');
      
      mappings.push({
        originalPath: originalFullPath,
        wrapperPath: wrapperFilePath,
      });
    }
  }

  return mappings;
}
